### ISSUE TITLE
[BUG] appliedwork is not under fleet-system namespace

### ISSUE THREAD

**Issue by circy9** [Azure/k8s-work-api#76]
Any reasons for the decision?

❯ k get appliedwork -A -o yaml
apiVersion: v1
items:
- apiVersion: multicluster.x-k8s.io/v1alpha1
  kind: AppliedWork
  metadata:
    creationTimestamp: "2022-07-21T18:54:25Z"
    generation: 1
    name: test-work
    resourceVersion: "36801"
    uid: d32ce2f2-a176-452f-9005-b87726d15907
  spec:
    workName: test-work
    workNamespace: bbxsnrmem

**Comment by aagusuab** [comment]
Applied work should be a cluster-scoped namespace, as it is watching over the manifests that may be deployed in other namespaces.
