### ISSUE TITLE
[BUG] Missing ordinal field for the first resource

### ISSUE THREAD

**Issue by circy9** [Azure/k8s-work-api#77]
❯ k get appliedwork -A -o yaml
apiVersion: v1
items:
- apiVersion: multicluster.x-k8s.io/v1alpha1
  kind: AppliedWork
  metadata:
    creationTimestamp: "2022-07-21T18:54:25Z"
    generation: 1
    name: test-work
    resourceVersion: "36801"
    uid: d32ce2f2-a176-452f-9005-b87726d15907
  spec:
    workName: test-work
    workNamespace: bbxsnrmem
  status:
    appliedResources:
    - group: apps
      kind: Deployment
      name: test-nginx
      namespace: default
      resource: deployments
      version: v1
    - kind: Service
      name: test-nginx
      namespace: default
      ordinal: 1
      resource: services
      version: v1

**Comment by aagusuab** [comment]
https://github.com/Azure/k8s-work-api/pull/89
