### ISSUE TITLE
[BUG] observedGeneration is wrong or unpopulated for manifestConditions

### ISSUE THREAD

**Issue by circy9** [Azure/k8s-work-api#79]
A. I applied example-work.yaml (both resources use default namespace) -> generation 1
B. I updated example-work.yaml to use a wrong namespace for both resources (both resources use bad namespace) -> generation 2
C. I reverted my change to resource 1 in example-work.yaml (resource 1 uses default namespace, resource 2 uses a bad namespace) -> generation 3.

A. Resource 1 has the right observedGeneration. Resource 2 is missing it.
    manifestConditions:
    - conditions:
      - lastTransitionTime: "2022-07-21T18:54:26Z"
        message: Apply manifest complete
        observedGeneration: 1
        reason: AppliedManifestComplete
        status: "True"
        type: Applied
      identifier:
        group: apps
        kind: Deployment
        name: test-nginx
        namespace: default
        resource: deployments
        version: v1
    - conditions:
      - lastTransitionTime: "2022-07-21T18:54:26Z"
        message: Apply manifest complete
        reason: AppliedManifestComplete
        status: "True"
        type: Applied
      identifier:
        kind: Service
        name: test-nginx
        namespace: default
        ordinal: 1
        resource: services
        version: v1

B. Both missing observed generations.
    manifestConditions:
    - conditions:
      - lastTransitionTime: "2022-07-21T19:03:25Z"
        message: 'Failed to apply manifest: namespaces "liqian" not found'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      identifier:
        group: apps
        kind: Deployment
        name: test-nginx
        namespace: liqian
        resource: deployments
        version: v1
    - conditions:
      - lastTransitionTime: "2022-07-21T19:03:25Z"
        message: 'Failed to apply manifest: namespaces "liqian" not found'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      identifier:
        kind: Service
        name: test-nginx
        namespace: liqian
        ordinal: 1
        resource: services
        version: v1

C. Resource 1 use the wrong observedGeneration=1. Resource 2 is missing it

    manifestConditions:
    - conditions:
      - lastTransitionTime: "2022-07-21T19:07:14Z"
        message: Apply manifest complete
        observedGeneration: 1
        reason: AppliedManifestComplete
        status: "True"
        type: Applied
      identifier:
        group: apps
        kind: Deployment
        name: test-nginx
        namespace: default
        resource: deployments
        version: v1
    - conditions:
      - lastTransitionTime: "2022-07-21T19:03:25Z"
        message: 'Failed to apply manifest: namespaces "liqian" not found'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      identifier:
        kind: Service
        name: test-nginx
        namespace: liqian
        ordinal: 1
        resource: services
        version: v1

**Comment by aagusuab** [comment]
After going through the exact steps, I found that the observed generation was working properly.
The service originally do not have observed generation, and the generation is determined by the generation of resources within the member cluster, not by the generation of the work.
