### ISSUE TITLE
[BUG BASH]: Should we allow user to delete the applied work CR

### ISSUE THREAD

**Issue by Arvindthiru** [Azure/k8s-work-api#80]
### **Describe the bug**
Deleting the applied work CR deletes all the applied manifests along with it

Deleting applied work and then deleting work on hub cluster never completes 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/17449572/180303871-6c5e76ff-eb26-408a-b420-e898523abeb2.png">

**Comment by Ealianis** [comment]
We can't stop the cluster owner from having access to delete this resource. This is issue is mitigate by our reconcile loops that will recreate the Appliedwork for the respective Work in the event that user deletes the AppliedWork on the member cluster.
