### ISSUE TITLE
[BUG] spec-hash only found in appliedwork not in work

### ISSUE THREAD

**Issue by circy9** [Azure/k8s-work-api#81]
There is no way for someone debugging the system to understand whether the spec in Work match the spec-hash in AppliedWork.

❯ k get deployment -o yaml
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      multicluster.x-k8s.io/spec-hash: 923e114d98ff748ddb45f8a3d58a529255aac363bbbd76c3238d6573d40dba85

**Comment by aagusuab** [comment]
The specHash is not needed in Work object, whenever manifests are updated / created, a new SpecHash is generated for each spec of Work, which then is compared to the spec-Hash in appliedWork.
