### ISSUE TITLE
[BUG] Appliedwork can't be recreated after deleted

### ISSUE THREAD

**Issue by circy9** [Azure/k8s-work-api#84]
I deleted appliedwork, and then changed work.

~/github/k8s-work-api master !1 ❯ k logs deploy-work-api-5bd97f8dff-9g7ws -n fleet-system

I0721 20:07:15.939707       1 finalize_controller.go:51] "Work finalize controller reconcile loop triggered." item="bbxsnrmem/test-work"
E0721 20:07:15.940527       1 finalize_controller.go:76] "resource retrieval failed" err="expected pointer, but got nil" AppliedWork="test-work"
1.658434035940577e+09	ERROR	controller.work	Reconciler error	{"reconciler group": "multicluster.x-k8s.io", "reconciler kind": "Work", "name": "test-work", "namespace": "bbxsnrmem", "error": "expected pointer, but got nil"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
I0721 20:07:15.940464       1 work_status_controller.go:65] "Work Status controller reconcile loop triggered" item="bbxsnrmem/test-work"
I0721 20:07:15.940883       1 apply_controller.go:73] "Work apply controller reconcile loop triggered." item="bbxsnrmem/test-work"
I0721 20:07:15.951624       1 resource_tracker.go:69] "appliedWork does not exist" item="bbxsnrmem/test-work"
E0721 20:07:15.951654       1 resource_tracker.go:79] "applied/work object existence not consistent" err="work controller didn't create the appliedWork bbxsnrmem/test-work" item="bbxsnrmem/test-work"
E0721 20:07:15.951672       1 apply_controller.go:102] "resource retrieval failed" err="appliedworks.multicluster.x-k8s.io \"test-work\" not found" AppliedWork="test-work"
1.6584340359516854e+09	ERROR	controller.work	Reconciler error	{"reconciler group": "multicluster.x-k8s.io", "reconciler kind": "Work", "name": "test-work", "namespace": "bbxsnrmem", "error": "work controller didn't create the appliedWork bbxsnrmem/test-work"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
1.658434035951714e+09	ERROR	controller.work	Reconciler error	{"reconciler group": "multicluster.x-k8s.io", "reconciler kind": "Work", "name": "test-work", "namespace": "bbxsnrmem", "error": "resource retrieval failed, AppliedWork=test-work: appliedworks.multicluster.x-k8s.io \"test-work\" not found", "errorVerbose": "appliedworks.multicluster.x-k8s.io \"test-work\" not found\nresource retrieval failed, AppliedWork=test-work\nsigs.k8s.io/work-api/pkg/controllers.(*ApplyWorkReconciler).Reconcile\n\t/workspace/pkg/controllers/apply_controller.go:104\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227

**Comment by aagusuab** [comment]
https://github.com/Azure/k8s-work-api/pull/96
