### ISSUE TITLE
[BUG] Can't delete work after deleting appliedwork manually

### ISSUE THREAD

**Issue by circy9** [Azure/k8s-work-api#85]
This command will hang.

❯ k delete -f example-work.yaml
work.multicluster.x-k8s.io "test-work" deleted

Here is what we observe from member cluster.

❯ k logs deploy-work-api-5bd97f8dff-9g7ws -n fleet-system
I0721 20:12:15.918009       1 finalize_controller.go:51] "Work finalize controller reconcile loop triggered." item="bbxsnrmem/test-work"
I0721 20:12:15.918075       1 work_status_controller.go:65] "Work Status controller reconcile loop triggered" item="bbxsnrmem/test-work"
I0721 20:12:15.918229       1 apply_controller.go:73] "Work apply controller reconcile loop triggered." item="bbxsnrmem/test-work"
I0721 20:12:15.918258       1 apply_controller.go:94] "resource is in the process of being deleted" Work="bbxsnrmem/test-work"
I0721 20:12:15.964965       1 resource_tracker.go:69] "appliedWork does not exist" item="bbxsnrmem/test-work"
E0721 20:12:15.964999       1 resource_tracker.go:79] "applied/work object existence not consistent" err="work controller didn't create the appliedWork bbxsnrmem/test-work" item="bbxsnrmem/test-work"
1.6584343359650366e+09	ERROR	controller.work	Reconciler error	{"reconciler group": "multicluster.x-k8s.io", "reconciler kind": "Work", "name": "test-work", "namespace": "bbxsnrmem", "error": "work controller didn't create the appliedWork bbxsnrmem/test-work"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
E0721 20:12:15.966602       1 finalize_controller.go:127] "resource retrieval failed" err="appliedworks.multicluster.x-k8s.io \"test-work\" not found" AppliedWork="test-work"
1.6584343359666426e+09	ERROR	controller.work	Reconciler error	{"reconciler group": "multicluster.x-k8s.io", "reconciler kind": "Work", "name": "test-work", "namespace": "bbxsnrmem", "error": "appliedworks.multicluster.x-k8s.io \"test-work\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227

**Comment by aagusuab** [comment]
https://github.com/Azure/k8s-work-api/pull/96
