### ISSUE TITLE
[BUG] Add additional condition types

### ISSUE THREAD

**Issue by ryanzhang-oss** [Azure/k8s-work-api#86]
### **Describe the bug**
IIRC, we are not implementing the conditions below. I think it will be good to have an Available condition.

	// Valid condition types are:
	// 1. Applied represents workload in Work is applied successfully on the spoke cluster.
	// 2. Progressing represents workload in Work in the trasitioning from one state to another the on the spoke cluster.
	// 3. Available represents workload in Work exists on the spoke cluster.
	// 4. Degraded represents the current state of workload does not match the desired

### **Additional context**
Please think through all the cases.

**Comment by aagusuab** [comment]
https://github.com/Azure/k8s-work-api/pull/97
